[package]
name = "wasi-calcit"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calcit = "0.5.33"
rpds = "0.11.0"
im_ternary_tree = "0.0.6"
cirru_edn = "0.2.17"
